import "@workspace/ui/globals.css";
import { Header } from "@/src/components/header/header.component";
import { ThemeProvider } from "@/src/core/context/theme.provider";
import type { Metadata } from "next";
import { Golos_Text } from "next/font/google";

const golosTextFonts = Golos_Text({
	variable: "--font-golos-text",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="pt-BR" suppressHydrationWarning>
			<body className={`${golosTextFonts.variable} antialiased`}>
				<ThemeProvider>
					<div className="flex flex-col h-full min-h-dvh">
						<main className="flex flex-col grow">
							<Header />
							<div className="flex justify-center items-center ">{children}</div>
						</main>
					</div>
				</ThemeProvider>
			</body>
		</html>
	);
}
